### ISSUE TITLE
Remove unused CSS and JS

### ISSUE THREAD

**Issue by nitishk72** [cpeditor/cpeditor.github.io#11]
I was seeing the coverage of the webiste and found that only 13% of code is being used. We need to remove the unused CSS and JavaScript.

![Screenshot](https://user-images.githubusercontent.com/15886737/75256805-10067f80-580a-11ea-9a1c-8cdb9de5bde5.png)

**Comment by coder3101** [comment]
@nitishk72

If you believe all useless css and js have been removed, you can mark this issue resolved.

**Comment by coder3101** [comment]
Closed for inactivity.
