### ISSUE TITLE
Add manual page

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor.github.io#13]
We can put [INSTALL.md](https://github.com/cpeditor/cpeditor/blob/master/doc/INSTALL.md) and [MANUAL.md](https://github.com/cpeditor/cpeditor/blob/master/doc/MANUAL.md) on the website.

**Comment by coder3101** [comment]
@nitishk72 It would be better if you could add a Static Site generator or some library that will fetch the above Markdown files from github and render its content into the website section, In this way we make sure that website need not to be updated everytime those Instructions change in Github.

This would be an interesting work, I have assigned it to you !

**Comment by ouuan** [comment]
We can even make a blog and put the changelogs and something else in it, the difference from a normal blog is that the main page is for promotion instead of a list of blogs.

**Comment by nitishk72** [comment]
I think we should go with Hugo. It's fast and simple

**Comment by coder3101** [comment]
@nitishk72 whatever you feel okay with. You can go with that

**Comment by ouuan** [comment]
I also vote for Hugo.
