### ISSUE TITLE
Nitish Add your testimonials

### ISSUE THREAD

**Issue by coder3101** [cpeditor/cpeditor.github.io#2]
In the repository source code you will find `index.html`. Inside of which you have to add your testimonial that should be exactly 3 lines long on website. You also need a add a picture of yourself on the same, simply add a picture to `img/testimonials/your-name.png`. This picture must be round and should have background white or transparent preferably.

This should be done ASAP @nitishk72 , Once you have done it and can see that your testimonials and picture are correct in the website at https://cpeditor.github.io

You should close this issue

**Comment by nitishk72** [comment]
added 👍
