### ISSUE TITLE
Unable to build and serve

### ISSUE THREAD

**Issue by nitishk72** [cpeditor/cpeditor.github.io#20]
<img width="1104" alt="Screenshot 2020-04-29 at 1 02 49 PM 1" src="https://user-images.githubusercontent.com/15886737/80571792-d248f180-8a1a-11ea-9a95-2d92a74da00f.png">

**Comment by coder3101** [comment]
You can open a PR within a minute on-rendere will serve the site ang give you a URL.

**Comment by ouuan** [comment]
You have to run `npm install` to install postcss.

**Comment by ouuan** [comment]
And you have to run `git submodule update --init --recursive` to get the submodules.
