### ISSUE TITLE
Spelling error in docs

### ISSUE THREAD

**Issue by shakeabi** [cpeditor/cpeditor.github.io#24]
The source code tab heading in the left menu is misspelt.

**Comment by ouuan** [comment]
Can you [edit this file](https://github.com/cpeditor/cpeditor.github.io/edit/hugo/content/en/docs/Source%20Code/_index.md) and propose a PR to fix it?

**Comment by ouuan** [comment]
Because it takes time for me to find where you are referring to, it's better to directly open a PR. You can jump to the editing page in the right sidebar on the website.

**Comment by ouuan** [comment]
@allcontributors add @shakeabi for reporting bugs.
