### ISSUE TITLE
Ouuan Add your testimonials

### ISSUE THREAD

**Issue by coder3101** [cpeditor/cpeditor.github.io#3]
In the repository source code you will find `index.html`. Inside of which you have to add your testimonial that should be exactly 3 lines long on website. You also need a add a picture of yourself on the same, simply add a picture to `img/testimonials/your-name.png`. This picture must be round and should have background white or transparent preferably.

This should be done ASAP @ouuan , Once you have done it and can see that your testimonials and picture are correct in the website at https://cpeditor.github.io

You should close this issue

**Comment by ouuan** [comment]
Are you sure we should add testimonials from maintainers?

**Comment by coder3101** [comment]
@ouuan Until we don't get real testimonials we should add something. I will create a Google form which we can share in blog and here so that we we can collect image and real testimonials.
