### ISSUE TITLE
526 Invalid SSL certificate

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor.github.io#337]
https://cpeditor.org/ is returning 526 Invalid SSL certificate (between Cloudflare and the source host).

https://archive.is/G9KhZ

**Comment by ouuan** [comment]
But why does this error happen? Isn't it hosted on GitHub Pages? Is the GitHub Pages certificate expired?

**Comment by coder3101** [comment]
Cloudflare TLS/SSL mode was set to strict which requires that origin and cloudflare talks with TLS. Now, something happened on Github pages (origin server) and it no longer served valid certificates. 

Now, I changed TLS/SSL to "flexible" which doesn't mandates TLS b/w origin and cloudflare.

**Comment by ouuan** [comment]
Yes, I know that. I'm wondering why GitHub Pages is not serving a valid certificate.

**Comment by ouuan** [comment]
What's the current DNS configuration?

ref: https://github.com/orgs/community/discussions/22398 https://github.com/orgs/community/discussions/23572

**Comment by coder3101** [comment]
It failed to provision/renew a certificate. If you check settings, you will find it says “it can take upto 24h to renew”. 

It could be because DNS is proxied through Cloudflare so the github domain verification check failed and new certs could not be issued.

**Comment by ouuan** [comment]
I'm not familiar with GitHub Pages behind Cloudflare. Is this a best practice? I would like either plain Github Pages or Cloudflare Pages instead.

**Comment by coder3101** [comment]
Cloudflare provides DNS, free HTTPS (TLS) support, best-in-class performance settings (gzip, SDCH, HTTP/2, sane Cache-Control and E-Tag headers, etc.), minification, etc.

Serving a website behind a CDN is a well known practice.
