### ISSUE TITLE
Add portable versions in documentation/installation and add download check for it

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor.github.io#38]
related: cpeditor/cpeditor#411

**Comment by ouuan** [comment]
What's the best place to put the download button for the portable version? :thinking:

Maybe we can have two checkboxes (platform and version) instead of several buttons?

**Comment by coder3101** [comment]
That seems a good idea, or maybe you can replace `Dll Missing` hyperlink with the download for `Get Portable version`
