### ISSUE TITLE
Make a download page

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor.github.io#5]
It can be like:

Three big icons Windows, Mac OS, and Linux, under each of them a big button "Get Stable Version" and a small button "Get Beta Version", and a complete list of all releases (the list can be on another page, possibly with a paginator or display only the latest 20~50 versions).

**Comment by coder3101** [comment]
@ouuan Also since master branch always serve the website, you should not work directly on it rather on some other branch like dev and your work is finished, merge it to master to deploy
